# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
  end

  config.vm.define "webserver01" do |machine|
      machine.vm.box = "trusty64"
      machine.vm.hostname = "machine"
      machine.vm.network "private_network", ip: "192.168.10.10"
      machine.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "webserver02" do |machine|
      machine.vm.box = "trusty32"
      machine.vm.hostname = "webserver02"
      machine.vm.network "private_network", ip: "192.168.10.11"
      machine.vm.synced_folder ".", "/vagrant", disabled: true
  end


  config.vm.define "webserver03" do |machine|
      machine.vm.box = "trusty32"
      machine.vm.hostname = "webserver03"
      machine.vm.network "private_network", ip: "192.168.10.12"
      machine.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "webserver04" do |machine|
      machine.vm.box = "trusty32"
      machine.vm.hostname = "webserver04"
      machine.vm.network "private_network", ip: "192.168.10.13"
      machine.vm.synced_folder ".", "/vagrant", disabled: true
  end

end
